name: riverpod_paging_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
